//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controlpermiso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Controlpermiso()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int idcontrol_permiso { get; set; }
        public string nombrecontrolpermiso { get; set; }
        public int idtipo_usuario { get; set; }
        public int idPermiso { get; set; }
        public bool estado { get; set; }
    
        public virtual Permiso Permiso { get; set; }
        public virtual Tipousuario Tipousuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
