//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactospaciente
    {
        public int idcontactospaciente { get; set; }
        public int idPaciente { get; set; }
        public string nombre_contacto1 { get; set; }
        public string nombre_contacto2 { get; set; }
        public string apellido_contacto1 { get; set; }
        public string apellido_contacto2 { get; set; }
        public Nullable<int> telefono { get; set; }
        public string direccion { get; set; }
        public int idDepartamento { get; set; }
        public int idMunicipio { get; set; }
        public bool estado { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
