//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadocita
    {
        public int idEstadocita { get; set; }
        public int idcita { get; set; }
        public int idPaciente { get; set; }
        public Nullable<int> idmedicamento { get; set; }
        public System.DateTime fecha_estadocita { get; set; }
        public string estado_citap { get; set; }
        public bool estado { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual Medicamento Medicamento { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
