//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHospital.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_hospitalEscUAIEntities : DbContext
    {
        public bd_hospitalEscUAIEntities()
            : base("name=bd_hospitalEscUAIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cita> Cita { get; set; }
        public virtual DbSet<Contactospaciente> Contactospaciente { get; set; }
        public virtual DbSet<Controlpermiso> Controlpermiso { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Estadocita> Estadocita { get; set; }
        public virtual DbSet<Estadopaciente> Estadopaciente { get; set; }
        public virtual DbSet<Estadotratamiento> Estadotratamiento { get; set; }
        public virtual DbSet<Institucion> Institucion { get; set; }
        public virtual DbSet<Medicamento> Medicamento { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<Prueba> Prueba { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<Tipopaciente> Tipopaciente { get; set; }
        public virtual DbSet<Tipousuario> Tipousuario { get; set; }
        public virtual DbSet<Tratamiento> Tratamiento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
