//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Cita = new HashSet<Cita>();
            this.Contactospaciente = new HashSet<Contactospaciente>();
            this.Estadocita = new HashSet<Estadocita>();
            this.Prueba = new HashSet<Prueba>();
            this.Tratamiento = new HashSet<Tratamiento>();
        }
    
        public int idPaciente { get; set; }
        public int idEstadopaciente { get; set; }
        public int idtipopaciente { get; set; }
        public int idUsuario { get; set; }
        public int idDepartamento { get; set; }
        public int idMunicipio { get; set; }
        public string Codigo_paciente { get; set; }
        public string Nombre_paciente1 { get; set; }
        public string Nombre_paciente2 { get; set; }
        public string Apellido_paciente1 { get; set; }
        public string Apellido_paciente2 { get; set; }
        public Nullable<System.DateTime> Fecha_nacimiento { get; set; }
        public Nullable<int> edad { get; set; }
        public string sexo { get; set; }
        public string orientacion_sexual { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string direccion { get; set; }
        public bool estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Cita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contactospaciente> Contactospaciente { get; set; }
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estadocita> Estadocita { get; set; }
        public virtual Estadopaciente Estadopaciente { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual Tipopaciente Tipopaciente { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prueba> Prueba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tratamiento> Tratamiento { get; set; }
    }
}
