//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prueba
    {
        public int idprueba { get; set; }
        public int idPaciente { get; set; }
        public string prueba_rapVIH { get; set; }
        public string carga_viral { get; set; }
        public string CD4 { get; set; }
        public string cripto { get; set; }
        public string histo { get; set; }
        public string TB_lam { get; set; }
        public string comentario { get; set; }
        public bool estado { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
