//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamiento
    {
        public int idtratamiento { get; set; }
        public int idPaciente { get; set; }
        public int idestadotratamiento { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public string nombre_tratamiento { get; set; }
        public string descripcion_tratamiento { get; set; }
        public bool estado { get; set; }
    
        public virtual Estadotratamiento Estadotratamiento { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
